name: Download k8s images.

on:
  push:
    branches:
      - master
    paths:
      - 'offlines/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, ok8s!
    - name: Download K8s images
      run: |
        cd offlines
        chmod +x ./download.sh
        ./download.sh -D
    - name: Login Docker Push images
      env:
        ACCESS_TOKEN: ${{ secrets.DOCKER_PW }} 
      run: |
        source offlines/version
        echo "PWD:${PWD}"
        cd offlines
        docker login -u wxdlong -p ${ACCESS_TOKEN}
        docker build . --file Dockerfile --tag wxdlong/ok8s:${k8sVersion}
        echo "push to docker hub"
        docker push wxdlong/ok8s:${k8sVersion}
        
        docker logout
        
        echo "push to aliyun"
        docker login --username=yjmnrg@gmail.com registry.cn-shanghai.aliyuncs.com -p ${ACCESS_TOKEN}
        docker push registry.cn-hangzhou.aliyuncs.com/wxdlong/ok8s:${k8sVersion}